/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import java.io.*;
import java.net.Socket;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        String servidor = args[0]; // 127.0.0.1
        int porta = Integer.parseInt(args[1]);

        Scanner teclado = new Scanner(System.in);


        try(Socket socket = new Socket(servidor, porta)){
            System.out.println("conectado no servidor...");

            // estabelecer fluxos de entrada e saída (I/O)
            BufferedReader entrada =  new BufferedReader(new InputStreamReader(socket.getInputStream()));

            OutputStreamWriter saida = new OutputStreamWriter(socket.getOutputStream(), "UTF-8");
            System.out.print(servidor + "> ");

             String mensagem = teclado.nextLine();
            saida.write(mensagem + "\n");

            saida.flush();

            String resposta = entrada.readLine();

            System.out.println("servidor falou: " + resposta);

        }catch (Exception e){
            System.err.println("Erro: " + e.toString());
        }

    }
}
